# Waveshare 25517 (ESP32-S3-Zero-M)
# https://www.espboards.dev/esp32/esp32-s3-zero/
# https://www.waveshare.com/esp32-s3-zero.htm

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  framework:
    type: esp-idf

# Configuration
substitutions:

  name: "esp-zero-argb"
  friendly_name: "ZERO ARGB Module"

  # Debug
  hide_diagnostic_components: "true"

  # Pinout
  pin_status_led:       5
  status_led_count:    22
  status_led_order:   GRB

packages:
  - !include packages/template.yaml
  - !include packages/status_led_ws2812.yaml

# ============================================================================

light:

  - id: !extend status_led_light
    name: "Komputer (LED)"
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: !remove


